### ISSUE TITLE
IE 11 issue: Invalid calling object

### ISSUE THREAD

**Issue by Landen13** [joe-tom/outclick#1] opened 2016-10-18 16:19 UTC
This error appears in IE 11.

**index.js - 88 line**
`removeEventListener(this, arguments)`

error:
 **Invalid calling object**

How can this be fixed?

**Comment by joe-tom** [comment] 2016-10-18 19:06
It's most likely caused by the removeEventListener function not being called in the context of the document. It should be fixed with a .call(). I'll fix it in a bit.

**Closed** 2016-10-21 05:37 UTC
